name: blockinsight7000

services:
  ch-keeper:
    image: clickhouse/clickhouse-keeper:25.11
    container_name: ch-keeper
    restart: unless-stopped
    ports:
      - "9181:9181"
    volumes:
      - ./keeper/config.xml:/etc/clickhouse-keeper/config.xml:ro
      - keeper_data:/var/lib/clickhouse
    command: >
      clickhouse-keeper
      --config-file=/etc/clickhouse-keeper/config.xml

  clickhouse:
    image: clickhouse/clickhouse-server:25.11
    container_name: clickhouse
    restart: unless-stopped
    depends_on:
      - ch-keeper
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
      - "9009:9009"   # interserver http
      - "9363:9363"   # Prometheus metrics
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml:ro
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml:ro
      - ./clickhouse/logs:/var/log/clickhouse-server/
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: blockinsight7000
      CLICKHOUSE_PASSWORD: e1uYl2Fs0bjMfb
      CLICKHOUSE_DB: blockinsight7000

  bitcoind-testnet:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoin-testnet
    restart: unless-stopped
    volumes:
      - bitcoind_testnet_data:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf

    ports:
      - "8332:8332"   # RPC
      - "8333:8333"   # P2P
      - "28332:28332" # ZMQ rawblock
      - "28333:28333" # ZMQ rawtx

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - clickhouse
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - clickhouse
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  btc-history-ingester:
    build:
      context: ../..
      dockerfile: ./build/utxo.Dockerfile
    container_name: btc-history-ingester
    entrypoint:
      - /usr/bin/utxo-history-ingester
    restart: unless-stopped
    depends_on:
      - clickhouse
      - bitcoind-testnet
    env_file:
      - ./envs/.env.btc-history-ingester

  btc-backfill-ingester:
    build:
      context: ../..
      dockerfile: ./build/utxo.Dockerfile
    container_name: btc-backfill-ingester
    entrypoint:
      - /usr/bin/utxo-backfill-ingester
    restart: unless-stopped
    depends_on:
      - clickhouse
      - bitcoind-testnet
    env_file:
      - ./envs/.env.btc-backfill-ingester

volumes:
  clickhouse_data:
  keeper_data:
  bitcoind_testnet_data:
  prometheus_data:
