apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    user: blockinsight7000
    secureJsonData:
      password: e1uYl2Fs0bjMfb
    jsonData:
      defaultDatabase: blockinsight7000
      serverVersion: auto
      timeout: 60
      querySettings:
        format: JSONEachRow
    isDefault: false
    editable: true
